import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../presentation/ui/layouts/Footer";
import Navigation from "../presentation/ui/layouts/Navigation";
import { AuthTokenProvider } from "../presentation/providers/AuthTokenProvider";
import ReactQueryProvider from "../presentation/providers/ReactQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "iSellShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-white`}
    >
      <body className="min-h-full flex flex-col text-black bg-white">
        <ReactQueryProvider>
          <AuthTokenProvider>
            <Navigation />
            <div className="flex-1 flex flex-col min-h-screen">
              {children}
              <Footer />
            </div>
          </AuthTokenProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
